[package]
name = "donut"
version = "0.1.0"
edition = "2018"

[dependencies]
bevy = { version = "0.5.0", features = ["dynamic"] }
bevy_rapier2d = { version = "0.11.0", features = [ "simd-stable" ] }
ldtk_rust = { version = "0.5.2" }
